### ISSUE TITLE
disable haskell-core ?

### ISSUE THREAD

**Issue by farseerfc** [yuyichao/devtools-cn#1]
Or split into a separate conf file so that normal archlinuxcn-*-build don't have them.

**Comment by yuyichao** [comment]
Any idea which package(s) needs the `haskell-core` repo?

**Comment by farseerfc** [comment]
It appears that `haskell-core` repo no longer works any more at http://xsounds.org/~haskell/core/ .
So can we remove it?

**Comment by yuyichao** [comment]
Sure....

I noticed that locally too but wasn't sure if it's specific to my ip....
